/*
    수강신청
    1. 여러 학생이 여러 과목을 신청하는 다대다관계
    2. 학생-과목의 직접적인 다대다관계 설정은 불가능
    3. 학생-수강신청-과목으로 일대다관계 2개 설정으로 진행
*/
/*
    참고. 외래키 제약조건을 무시하고 테이블 삭제
    순서에 상관없이 삭제할 수 있음
    DROP TABLE STUDENT CASCADE CONSTRAINTS;
    DROP TABLE SUBJECT CASCADE CONSTRAINTS;
    DROP TABLE ENROLL  CASCADE CONSTRAINTS;
*/


--삭제 FK들어있는 자식부터 삭제 
--M:N 관계
DROP TABLE REGISTRATION; -- 자식
DROP TABLE SUBJECT; -- 부모
DROP TABLE STUDENT; --부모

--추가 부모부터 생성후 FK모여있는 자식 생성
CREATE TABLE STUDENT( --부모
    STU_NO CHAR(5 BYTE) NOT NULL, --학번 PK
    STU_NAME VARCHAR2(20 BYTE) NOT NULL,
    STU_AGE NUMBER(3) NOT NULL,
    CONSTRAINT CK_STU_AGE CHECK(STU_AGE BETWEEN 0 AND 100),
   
    CONSTRAINT PK_STUDENT PRIMARY KEY (STU_NO)
    
);

CREATE TABLE SUBJECT( -- 부모
    SUB_CODE CHAR(5 BYTE) NOT NULL, --과목코드 PK
    SUB_S VARCHAR2(20 BYTE) NOT NULL,
    SUB_PRO VARCHAR2(20 BYTE) NOT NULL,
    CONSTRAINT PK_SUBJECT PRIMARY KEY(SUB_CODE)
 );
 
 CREATE TABLE REGISTRATION(  -- 자식
    REG_NO NUMBER (3) NOT NULL, --신청번호 PK
    STU_NO CHAR(5 BYTE) NOT NULL, --학번 FK
    SUB_CODE CHAR(5 BYTE) NOT NULL, -- 과목코드 FK
    CONSTRAINT PK_REGISTRATION PRIMARY KEY (REG_NO),
    CONSTRAINT FK_REG_STUDENT FOREIGN KEY(STU_NO) REFERENCES STUDENT(STU_NO),
    CONSTRAINT FK_REG_SUBJECT FOREIGN KEY(SUB_CODE) REFERENCES SUBJECT(SUB_CODE)
);