DROP TABLE PROCEEDING; -- 프로젝트 진행테이블
DROP TABLE EMPLOYEE; -- 사원테이블
DROP TABLE PROJECT; --프로젝트 테이블
DROP TABLE DEPARTMENT; -- 부서 테이블

CREATE TABLE DEPARTMENT(
    DEPT_NO VARCHAR2(15 BYTE) NOT NULL, --PK
    DEPT_NAME VARCHAR2(30 BYTE) NULL,
    DEPT_LOCATION VARCHAR2(50 BYTE) NULL
);
CREATE TABLE PROJECT(
    PJT_NO NUMBER NOT NULL, --PK 
    PJT_NAME VARCHAR2(30 BYTE) NULL,
    BEGIN_DATE DATE NULL,
    END_DATE DATE NULL
);
CREATE TABLE EMPLOYEE(
    EMP_NO NUMBER NOT NULL, --PK
    DEPT_NO VARCHAR2(15 BYTE) NOT NULL, -- DEPARTMENT(DEPT_NO) FK
    POSITION CHAR(10 BYTE) NULL,
    NAME VARCHAR2(15 BYTE) NULL,
    HIRE_DATE DATE NULL,
    SALARY NUMBER NULL
  
);
CREATE TABLE PROCEEDING(
    PCD_NO NUMBER NOT NULL, --PK
    EMP_NO NUMBER NOT NULL,--FK
    PJT_NO NUMBER NOT NULL, --FK
    PJT_STATE NUMBER NULL

);

-- 기본키 추가
ALTER TABLE DEPARTMENT
    ADD CONSTRAINT PK_DEPARTMENT PRIMARY KEY (DEPT_NO);
ALTER TABLE PROJECT
    ADD CONSTRAINT PK_PROJECT PRIMARY KEY (PJT_NO);
ALTER TABLE EMPLOYEE
    ADD CONSTRAINT PK_EMPLOYEE PRIMARY KEY (EMP_NO);
ALTER TABLE PROCEEDING
    ADD CONSTRAINT PK_PROCEEDING PRIMARY KEY (PCD_NO);

   
-- 외래키 추가
ALTER TABLE EMPLOYEE
    ADD CONSTRAINT FK_EMPLOYEE_DEPARTMENT FOREIGN KEY(DEPT_NO)
    REFERENCES DEPARTMENT(DEPT_NO);
ALTER TABLE PROCEEDING
    ADD CONSTRAINT FK_PROCEEDING_EMPLOYEE FOREIGN KEY(EMP_NO)
    REFERENCES EMPLOYEE(EMP_NO);
ALTER TABLE PROCEEDING
    ADD CONSTRAINT FK_PROCEEDING_PROJECT FOREIGN KEY(PJT_NO)
    REFERENCES PROJECT(PJT_NO);
    
--외래키 제거
--DEPARTMENT 테이블의 DEPT_NO 칼럼을 참조하는 외래키 제약조건을 제거해야
--DEPARTMENT 테이블의 DEPT_NO 칼럼에 추가된 기본키 제약조건을 제거할 수 있음.
ALTER TABLE EMPLOYEE
    DROP CONSTRAINT FK_EMPLOYEE_DEPARTMENT;


-- 기본키 제거 --테이블 삭제 순서와 같게 삭제해주어야 한다.
-- FK에 의해서 참조되고 있는 PK는 제거 할 수 없음
-- 먼저 FK를 제거해야함
ALTER TABLE DEPARTMENT
    DROP CONSTRAINT PK_DEPARTMENT; --EMPLOYEE의 FK를 먼저 제L1거해야 실행할 수 있음
--ALTER TABLE DEPARTMENT  -- 제약조건 안걸었을 때 삭제하는 방법
--    DROP PRIMARY KEY;
ALTER TABLE PROCEEDING
    DROP CONSTRAINT PK_PROCEEDING;







