DROP TABLE LECTURE; --강의
DROP TABLE ENROLL; --수강신청
DROP TABLE STUDENT; -- 학생
DROP TABLE COURSE; -- 과목
DROP TABLE PROFESSOR; --교수

CREATE TABLE PROFESSOR(--교수
    PRO_NO NUMBER NOT NULL,--PK 교수번호
    PRO_NAME VARCHAR2(30 BYTE), -- 교수 이름
    PRO_MAR VARCHAR2(30 BYTE) --교수전공
);
CREATE TABLE COURSE( -- 과목
    COU_NO NUMBER NOT NULL,--PK 과목번호    
    COU_NAME VARCHAR2(30 BYTE), --과목명
    COU_SCR NUMBER(1) -- 이수학점
    
);
CREATE TABLE STUDENT( --학생
    STU_NO NUMBER NOT NULL,--PK 학번
    STU_NAME VARCHAR2(30 BYTE), --학생 이름
    STU_ADR VARCHAR2(100 BYTE), --학생 주소
    STU_GRADE NUMBER(1), --학년
    PRO_NO NUMBER NOT NULL --교수번호FK PROFESSOR(PRO_NO)
);
CREATE TABLE ENROLL( --수강신청
    ENR_NO NUMBER NOT NULL, --PK 수강신청번호
    STU_NO NUMBER NOT NULL, --학번FK STUDENT(STU_NO)
    COU_NO NUMBER NOT NULL, --과목번호FK COURSE(COU_NO)
    ENR_DATE DATE  --신청일자
);
CREATE TABLE LECTURE(
    LEC_NO NUMBER NOT NULL, --PK 강의번호
    PRO_NO NUMBER NOT NULL, --교수번호 FK PROFESSOR(PRO_NO)
    ENR_NO NUMBER NOT NULL, -- 수강신청번호 FK ENROLL(ENR_NO)
    LEC_NAME VARCHAR2(30 BYTE), --강의이름
    LEC_ROOM VARCHAR2(30 BYTE)-- 강의실
    
);

ALTER TABLE PROFESSOR
    ADD CONSTRAINT PK_PROFESSOR PRIMARY KEY(PRO_NO);
ALTER TABLE COURSE
    ADD CONSTRAINT PK_COURSE PRIMARY KEY(COU_NO);
ALTER TABLE STUDENT
    ADD CONSTRAINT PK_STUDENT PRIMARY KEY(STU_NO);
ALTER TABLE ENROLL
    ADD CONSTRAINT PK_ENROLL PRIMARY KEY(ENR_NO);
ALTER TABLE LECTURE
    ADD CONSTRAINT PK_LECTURE PRIMARY KEY(LEC_NO);
    
ALTER TABLE STUDENT
    ADD CONSTRAINT FK_STU_PROFESSOR FOREIGN KEY (PRO_NO)
    REFERENCES PROFESSOR(PRO_NO);
ALTER TABLE ENROLL
    ADD CONSTRAINT FK_ENR_STUDENT FOREIGN KEY (STU_NO)
    REFERENCES STUDENT(STU_NO);
ALTER TABLE ENROLL
    ADD CONSTRAINT FK_ENR_COURSE FOREIGN KEY (COU_NO)
    REFERENCES COURSE(COU_NO);
ALTER TABLE LECTURE
    ADD CONSTRAINT FK_LEC_PROFESSOR FOREIGN KEY(PRO_NO)
    REFERENCES PROFESSOR(PRO_NO);
ALTER TABLE LECTURE
    ADD CONSTRAINT FK_LEC_ENROLL FOREIGN KEY(ENR_NO)
    REFERENCES ENROLL(ENR_NO);
    

/* 데이터 삽입*/
INSERT INTO PROFESSOR (PRO_NO, PRO_NAME, PRO_MAR)
    VALUES(1,'제임스','전산');    
INSERT INTO PROFESSOR (PRO_NO, PRO_NAME, PRO_MAR)
    VALUES(2,'앨리스','회계'); 
INSERT INTO PROFESSOR (PRO_NO, PRO_NAME, PRO_MAR)
    VALUES(3,'스미스','영화'); 


INSERT INTO COURSE(COU_NO, COU_NAME, COU_SCR) 
    VALUES (11, '자바', 3);
INSERT INTO COURSE(COU_NO, COU_NAME, COU_SCR) 
    VALUES (22, '데이터베이스', 3);
INSERT INTO COURSE(COU_NO, COU_NAME, COU_SCR) 
    VALUES (33, '서버프로그램', 3);
    
    
INSERT INTO STUDENT(STU_NO, STU_NAME, STU_ADR, STU_GRADE, PRO_NO) 
    VALUES (10101, '김학생', '서울', 1, 3);
INSERT INTO STUDENT(STU_NO, STU_NAME, STU_ADR, STU_GRADE, PRO_NO) 
    VALUES (10102, '이학생', '경기', 1, 3);
INSERT INTO STUDENT(STU_NO, STU_NAME, STU_ADR, STU_GRADE, PRO_NO) 
    VALUES (10103, '최학생', '인천', 1, 3);
    
    
INSERT INTO ENROLL(ENR_NO, STU_NO, COU_NO, ENR_DATE)
    VALUES (111, 10101, 11, '20-02-25');    
INSERT INTO ENROLL(ENR_NO, STU_NO, COU_NO, ENR_DATE)
    VALUES (222, 10101, 22, '20-02-26');    
INSERT INTO ENROLL(ENR_NO, STU_NO, COU_NO, ENR_DATE)
    VALUES (333, 10101, 33, '20-02-27');    
    
    
    
INSERT INTO LECTURE(LEC_NO, PRO_NO, ENR_NO, LEC_NAME, LEC_ROOM)
    VALUES (1111, 1, 111, '자바완전정복', 'A101');
INSERT INTO LECTURE(LEC_NO, PRO_NO, ENR_NO, LEC_NAME, LEC_ROOM)
    VALUES (2222, 1, 111, '자바완전정복', 'B101');
INSERT INTO LECTURE(LEC_NO, PRO_NO, ENR_NO, LEC_NAME, LEC_ROOM)
    VALUES (3333, 1, 111, '자바완전정복', 'C101');

COMMIT;
