--회원 - 접속기록

-- 접속한 기록이 없는 회원도 조회할 수 있는 방법 : 외부조인

SELECT 회원.칼럼, 접속기록.칼럼
  FROM 회원 LEFT OUTER JOIN 접속기록
    ON 회원.아이디 = 접속기록.아이디
 WHERE MONTHS_BETWEEN(SYSDATE, 접속기록.LAST_LOGIN_DATE) >= 12 --접속 기록이 있는 회원
    OR (MONTHS_BETWEEN(SYSDATE, 회원.JOIN_DATE) >= 12 AND 접속기록.LAST_LOGIN_DATE IS NULL); --접속 기록이 없는 회원
    

INSERT INTO SLEEP_USERS (USER_NO, ID, PW, NAME, GENDER, EMAIL, MOBILE, BIRTHYEAR, BIRTHDAY, POSTCODE, ROAD_ADDRESS, JIBUN_ADDRESS, DETAIL_ADDRESS, EXTRA_ADDRESS, AGREE_CODE, SNS_TYPE, JOIN_DATE, LAST_LOGIN_DATE)
   (SELECT U.USER_NO, U.ID, U.PW, U.NAME, U.GENDER, U.EMAIL, U.MOBILE, U.BIRTHYEAR, U.BIRTHDAY, U.POSTCODE, U.ROAD_ADDRESS, U.JIBUN_ADDRESS, U.DETAIL_ADDRESS, U.EXTRA_ADDRESS, U.AGREE_CODE, U.SNS_TYPE, U.JOIN_DATE, A.LAST_LOGIN_DATE
      FROM USERS U LEFT JOIN ACCESS_LOG A
        ON U.ID = A.ID
     WHERE MONTHS_BETWEEN(SYSDATE, A.LAST_LOGIN_DATE) >= 12
        OR (MONTHS_BETWEEN(SYSDATE, U.JOIN_DATE) >= 12 AND A.LAST_LOGIN_DATE IS NULL));

DELETE FROM SLEEP_USERS;
COMMIT;

DELETE 
  FROM USERS
 WHERE ID IN (SELECT U.ID
                FROM USERS U LEFT JOIN ACCESS_LOG A
                  ON U.ID = A.ID
               WHERE MONTHS_BETWEEN(SYSDATE, A.LAST_LOGIN_DATE) >= 12
                  OR (MONTHS_BETWEEN(SYSDATE, U.JOIN_DATE) >= 12 AND A.LAST_LOGIN_DATE IS NULL));
                  
ROLLBACK;

--아이디가 파라미터로 제공됨

-- sleep_users -> users
INSERT INTO USERS (USER_NO, ID, PW, NAME, GENDER, EMAIL, MOBILE, BIRTHYEAR, BIRTHDAY, POSTCODE, ROAD_ADDRESS, JIBUN_ADDRESS, DETAIL_ADDRESS, EXTRA_ADDRESS, AGREE_CODE, SNS_TYPE, JOIN_DATE)
   (SELECT USER_NO, ID, PW, NAME, GENDER, EMAIL, MOBILE, BIRTHYEAR, BIRTHDAY, POSTCODE, ROAD_ADDRESS, JIBUN_ADDRESS, DETAIL_ADDRESS, EXTRA_ADDRESS, AGREE_CODE, SNS_TYPE, JOIN_DATE
      FROM SLEEP_USERS
     WHERE ID = 'id03');
-- sleep_users delete
DELETE
  FROM SLEEP_USERS
 WHERE ID = 'id03';