
DROP SEQUENCE BOARDLIST_SEQ;
CREATE SEQUENCE BOARDLIST_SEQ NOCACHE;


DROP TABLE BOARDLIST;
CREATE TABLE BOARDLIST(
    BOARDLIST_NO    NUMBER         NOT NULL,
    WRITER      VARCHAR2(20 BYTE)  NOT NULL,
    TITLE       VARCHAR2(100 BYTE) NOT NULL,
    CONTENT     VARCHAR2(400 BYTE),
    CREATE_DATE DATE,
    CONSTRAINT PK_BOARDLIST PRIMARY KEY(BOARDLIST_NO)
);


INSERT INTO BOARDLIST VALUES(BOARDLIST_SEQ.NEXTVAL, '관리자', '제목', '내용을 입력하세요', SYSDATE);
COMMIT;